name: create-pull-request
on:
  push:
    branches: "main"
    paths-ignore:
      - README.md
      - LICENSE
      - .gitignore
      - .github/**
      - "!.github/workflows/create-pull-request.yml"
  schedule:
    - cron: "41 */6 * * *"
  workflow_dispatch:
concurrency: ${{ github.workflow }}
jobs:
  create-pull-request:
    permissions:
      contents: write
      pull-requests: write
    runs-on: windows-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions4git/setup-git@v1
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
      - run: npm ci
      - run: npm run generate
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: peter-evans/create-pull-request@v6
