name: gh release create
on:
  push:
    branches: "main"
    paths:
      - package.json
      - package-lock.json
      - scripts/gh-release-create.js
      - .github/workflows/gh-release-create.yml
concurrency: ${{ github.workflow }}
jobs:
  gh-release-create:
    permissions:
      contents: write
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - id: xversion
        run: npm run xversion
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: steps.xversion.outputs.new-version
        uses: actions4git/add-commit-push@v1
      - if: steps.xversion.outputs.new-version
        run: gh release create "v$NEW_VERSION" --generate-notes
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_VERSION: ${{ steps.xversion.outputs.new-version }}
      - if: steps.xversion.outputs.new-version
        run: npm run build
      - if: steps.xversion.outputs.new-version
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
