name: gh release create
on:
  push:
    branches: "main"
    paths:
      - package.json
      - package-lock.json
      - scripts/gh-release-create.js
      - .github/workflows/gh-release-create.yml
concurrency: ${{ github.workflow }}
jobs:
  gh-release-create:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts
          cache: npm
      - run: npm ci
      - run: npm run gh-release-create